[package]
name = "spacejam-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"
name = "builder"

[dependencies]
anyhow.workspace = true
jam-types.workspace = true
