[workspace]
members = ["crates/*", "services/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["clearloop <tianyi.gc@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/spacejamapp/jade"

[workspace.dependencies]
builder = { path = "crates/builder", package = "spacejam-builder" }
cjam = { path = "crates/cli", package = "cargo-jam" }
testing = { path = "crates/testing", package = "jade-testing" }

# jam dependencies
bounded-collections = { version = "0.3.2", default-features = false }
jam-types = { path = "crates/jam-types", version = "0.1.22", default-features = false }
jam-pvm-builder = "0.1.22"
jam-pvm-common = { path = "crates/jam-pvm-common", version = "0.1.22", default-features = false }
jam-program-blob = { version = "0.1.22", default-features = false }
polkavm-linker = "0.24.0"
polkavm-derive = "0.24.0"
polkavm-common = "0.24.0"
podec = { version = "0.1.0", package = "jam-codec", default-features = false, features = [
    "derive",
] }

# crates.io
anyhow = "1.0.93"
async-graphql = "7.0.17"
async-graphql-axum = "7.0.16"
axum = "0.8.4"
clap = "4.5.30"
etc = "0.1.20"
dirs = "6.0.0"
hex = "0.4.3"
jobserver = "0.1.33"
quote = "1.0.33"
serde = { version = "1.0.215", features = ["derive"], default-features = false }
serde_json = "1.0.133"
sqlx = "0.8.5"
syn = "2.0.90"
temp-dir = "0.1.16"
time = "0.3.41"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tokio = "1.42.0"
tokio-stream = "0.1.17"
toml = { version = "0.8.19", features = ["parse"] }
tower = "0.5.1"
tower-http = { version = "0.6.1", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# spacejam dependencies
runtime = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "spacejam-runtime" }
codec = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "jamcodec" }
network = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "spacejam-network" }
score = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "spacejam-core" }
spacejam = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main" }
pvm = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "pvm" }
pvmi = { git = "https://github.com/spacejamapp/spacejam.git", branch = "main", package = "pvmi" }

[patch.crates-io]
jam-types = { path = "crates/jam-types" }
jam-pvm-common = { path = "crates/jam-pvm-common" }
