[package]
name = "jade"
edition.workspace = true
version.workspace = true

[dependencies]
jam-pvm-common.workspace = true

[features]
default = ["std"]
std = ["jam-pvm-common/std"]
tiny = ["jam-pvm-common/tiny"]
authorizer = ["jam-pvm-common/authorizer"]
service = ["jam-pvm-common/service"]
logging = ["jam-pvm-common/logging"]
