[package]
name = "jade-testing"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cjam.workspace = true
etc.workspace = true
spacevm.workspace = true
serde.workspace = true
service.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
