name: CI
on:
  push:
    branches: [main, jadex]
  pull_request:
    branches: [main, jadex]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@sccache
      - uses: taiki-e/install-action@nextest
      - name: Setup Token
      run: |
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.SPACEJAM_TOKEN }}@github.com" > ~/.git-credentials
      - name: Run Tests
        run: cargo nextest run --workspace --no-fail-fast --release

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all -- -D warnings
