name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Toolchain
        run: |
          rustup toolchain install 1.90.0
          rustup component add rust-src --toolchain 1.90.0
          rustup update stable && rustup default stable
          rustup component add clippy rustfmt
      - uses: taiki-e/install-action@sccache
      - uses: taiki-e/install-action@nextest
      - name: Run Tests
        run: cargo nextest run --no-fail-fast --release

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Toolchain
        run: |
          rustup toolchain install 1.90.0
          rustup component add rust-src --toolchain 1.90.0
          rustup update stable && rustup default stable
          rustup component add clippy rustfmt
      - uses: crate-ci/typos@v1.24.5
      - uses: taiki-e/install-action@sccache
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all -- -D warnings
