name: Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TERM: xterm-256color

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.24.5
